In [1]:
import sys,os, json
from pathlib import Path
import numpy as np
import pandas as pd
sys.path.append('../Clustering/')
import clusterSummary as CS
from importlib import reload  # Python 3.4+ only.

In [2]:
animal = 'Li'
oakPath = Path('/mnt/o/giocomo/alexg/Clustered/',animal)
localPath = Path('/mnt/c/Users/alexg8/Documents/Data/',animal,'Clustered')

In [9]:
with (oakPath/'Li_ClusteringSummary.json').open() as f:
    x=json.load(f)

In [29]:
x['Li']['060418']['T3g']['cell_IDs']

y=x['Li']['060418']['T3g']['cell_IDs']
for k,v in y.items():
    print(k,v)

1 []
2 []
3 [1, 8]
4 []
5 []
6 []
7 [0]
8 [7, 8]
9 []
10 []
11 []
12 []
13 []
14 []
15 []
16 []

In [38]:
ttPath = (oakPath/'Li_OF_052818_KSClusters'/'tt_10')

In [43]:
sp = np.load(ttPath / 'spike_times.npy')

In [41]:
cl = np.load(ttPath / 'spike_clusters.npy')

array([     432,      593,     1485, ..., 25342578, 25343024, 25343059],
      dtype=uint64)

In [47]:
CS=reload(CS)
#CS.CopyClustersToOak(localPath,oakPath)
x=CS.UpdateClusterInfo(oakPath,animal,localPath)

Making New Summary File.

Session Li_OF_052818_KSClusters no TTs clustered.

Session Li_OF_052918_KSClusters no TTs clustered.

Session Li_OF_053018_KSClusters no TTs clustered.

Session Li_OF_053118_KSClusters no TTs clustered.

Session Li_OF_060118_KSClusters no TTs clustered.

Session Li_OF_060418_KSClusters no TTs clustered.

Results for Li_OF_060518_KSClusters:
 nCells = 0
 nMuas = 3

Session Li_OF_060718_KSClusters no TTs clustered.

Session Li_OF_060818_KSClusters no TTs clustered.

Session Li_OF_061118_KSClusters no TTs clustered.

Session Li_OF_061218_KSClusters no TTs clustered.

Session Li_OF_061318_KSClusters no TTs clustered.

Session Li_OF_061418_KSClusters no TTs clustered.

Session Li_OF_061518_KSClusters no TTs clustered.

Session Li_OF_061818_KSClusters no TTs clustered.

Session Li_OF_062018_KSClusters no TTs clustered.

Session Li_OF_062518_KSClusters no TTs clustered.

Session Li_OF_062618_KSClusters no TTs clustered.

Session Li_OF_062718_KSClusters no TTs clustered.

Session Li_OF_062818_KSClusters no TTs clustered.

Session Li_OF_062918_KSClusters no TTs clustered.

Session Li_OF_070218_KSClusters no TTs clustered.

Session Li_OF_070618_KSClusters no TTs clustered.

Session Li_OF_071018_KSClusters no TTs clustered.

Session Li_OF_080118_KSClusters no TTs clustered.

Session Li_OF_080218_KSClusters no TTs clustered.

Session Li_T3g_052818_KSClusters no TTs clustered.

Session Li_T3g_052918_KSClusters no TTs clustered.

Session Li_T3g_053018_KSClusters no TTs clustered.

Session Li_T3g_053118_KSClusters no TTs clustered.

Results for Li_T3g_060118_KSClusters:
 nCells = 9
 nMuas = 17

Results for Li_T3g_060418_KSClusters:
 nCells = 5
 nMuas = 17

Results for Li_T3g_061318_KSClusters:
 nCells = 6
 nMuas = 11

Results for Li_T3g_061518_KSClusters:
 nCells = 3
 nMuas = 12

Results for Li_T3g_061818_KSClusters:
 nCells = 8
 nMuas = 14

Results for Li_T3g_062018_KSClusters:
 nCells = 10
 nMuas = 12

Results for Li_T3g_062518_KSClusters:
 nCells = 10
 nMuas = 16

Results for Li_T3g_062618_KSClusters:
 nCells = 9
 nMuas = 17

Results for Li_T3g_062718_KSClusters:
 nCells = 16
 nMuas = 13

Results for Li_T3g_062818_KSClusters:
 nCells = 10
 nMuas = 16

Session Li_T3g_070218_KSClusters no TTs clustered.

Session Li_T3g_070518_KSClusters no TTs clustered.

Session Li_T3g_070618_KSClusters no TTs clustered.

Session Li_T3g_070918_KSClusters no TTs clustered.

Session Li_T3g_071018_KSClusters no TTs clustered.

Session Li_T3g_071118_KSClusters no TTs clustered.

Session Li_T3g_072518_KSClusters no TTs clustered.

Session Li_T3g_072618_KSClusters no TTs clustered.

Session Li_T3g_073018_KSClusters no TTs clustered.

Session Li_T3g_080118_KSClusters no TTs clustered.

Session Li_T3g_080218_KSClusters no TTs clustered.

Session Li_T3g_080318_KSClusters no TTs clustered.

Session Li_T3g_080618_KSClusters no TTs clustered.

Session Li_T3g_080718_KSClusters no TTs clustered.

Session Li_T3i_060518_KSClusters no TTs clustered.

Session Li_T3i_060618_KSClusters no TTs clustered.

Session Li_T3i_060818_KSClusters no TTs clustered.

Session Li_T3i_061118_KSClusters no TTs clustered.

Session Li_T3i_061218_KSClusters no TTs clustered.
File Saved locally.
File Saved into OAK
Error updating session Li_OF_060518
Error <class 'KeyError'> 'OF' 141
              SessionDate Task Animal  Clustered  nCells  nMua  BestTT
Li_OF_052818       052818   OF     Li          0       0     0       0
Li_OF_052918       052918   OF     Li          0       0     0       0
Li_OF_053018       053018   OF     Li          0       0     0       0
Li_OF_053118       053118   OF     Li          0       0     0       0
Li_OF_060118       060118   OF     Li          0       0     0       0
Li_OF_060418       060418   OF     Li          0       0     0       0
Li_OF_060518       060518   OF     Li          1       0     0       0
Li_OF_060718       060718   OF     Li          0       0     0       0
Li_OF_060818       060818   OF     Li          0       0     0       0
Li_OF_061118       061118   OF     Li          0       0     0       0
Li_OF_061218       061218   OF     Li          0       0     0       0
Li_OF_061318       061318   OF     Li          0       0     0       0
Li_OF_061418       061418   OF     Li          0       0     0       0
Li_OF_061518       061518   OF     Li          0       0     0       0
Li_OF_061818       061818   OF     Li          0       0     0       0
Li_OF_062018       062018   OF     Li          0       0     0       0
Li_OF_062518       062518   OF     Li          0       0     0       0
Li_OF_062618       062618   OF     Li          0       0     0       0
Li_OF_062718       062718   OF     Li          0       0     0       0
Li_OF_062818       062818   OF     Li          0       0     0       0
Li_OF_062918       062918   OF     Li          0       0     0       0
Li_OF_070218       070218   OF     Li          0       0     0       0
Li_OF_070618       070618   OF     Li          0       0     0       0
Li_OF_071018       071018   OF     Li          0       0     0       0
Li_OF_080118       080118   OF     Li          0       0     0       0
Li_OF_080218       080218   OF     Li          0       0     0       0
Li_T3g_052818      052818  T3g     Li          0       0     0       0
Li_T3g_052918      052918  T3g     Li          0       0     0       0
Li_T3g_053018      053018  T3g     Li          0       0     0       0
Li_T3g_053118      053118  T3g     Li          0       0     0       0
Li_T3g_060118      060118  T3g     Li          1       9    17      10
Li_T3g_060418      060418  T3g     Li          1       5    17       3
Li_T3g_061318      061318  T3g     Li          1       6    11       7
Li_T3g_061518      061518  T3g     Li          1       3    12       3
Li_T3g_061818      061818  T3g     Li          1       8    14       8
Li_T3g_062018      062018  T3g     Li          1      10    12      10
Li_T3g_062518      062518  T3g     Li          1      10    16      10
Li_T3g_062618      062618  T3g     Li          1       9    17      10
Li_T3g_062718      062718  T3g     Li          1      16    13       8
Li_T3g_062818      062818  T3g     Li          1      10    16      10
Li_T3g_070218      070218  T3g     Li          0       0     0       0
Li_T3g_070518      070518  T3g     Li          0       0     0       0
Li_T3g_070618      070618  T3g     Li          0       0     0       0
Li_T3g_070918      070918  T3g     Li          0       0     0       0
Li_T3g_071018      071018  T3g     Li          0       0     0       0
Li_T3g_071118      071118  T3g     Li          0       0     0       0
Li_T3g_072518      072518  T3g     Li          0       0     0       0
Li_T3g_072618      072618  T3g     Li          0       0     0       0
Li_T3g_073018      073018  T3g     Li          0       0     0       0
Li_T3g_080118      080118  T3g     Li          0       0     0       0
Li_T3g_080218      080218  T3g     Li          0       0     0       0
Li_T3g_080318      080318  T3g     Li          0       0     0       0
Li_T3g_080618      080618  T3g     Li          0       0     0       0
Li_T3g_080718      080718  T3g     Li          0       0     0       0
Li_T3i_060518      060518  T3i     Li          0       0     0       0
Li_T3i_060618      060618  T3i     Li          0       0     0       0
Li_T3i_060818      060818  T3i     Li          0       0     0       0
Li_T3i_061118      061118  T3i     Li          0       0     0       0
Li_T3i_061218      061218  T3i     Li          0       0     0       0
File Saved to /mnt/o/giocomo/alexg/Clustered/Li
File Saved to /mnt/o/giocomo/alexg/Clustered/Li

 Overall Summary for Li :
 nSessions = 36
 nClusteredSessions 10
 nCells = 86
 nMua = 145

In [29]:
x=pd.DataFrame()

{'Li': {'052818': {'T3g': {'session': 'Li_T3g_052818_KSClusters',
    'Clustered': 0,
    'nCells': 0,
    'nMua': 0,
    'cell_IDs': {},
    'mua_IDs': {},
    'dateClustered': {},
    'unClustered_TTs': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    'All_TTs_Clustered': 0}},
  '052918': {'T3g': {'session': 'Li_T3g_052918_KSClusters',
    'Clustered': 0,
    'nCells': 0,
    'nMua': 0,
    'cell_IDs': {},
    'mua_IDs': {},
    'dateClustered': {},
    'unClustered_TTs': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    'All_TTs_Clustered': 0}},
  '053018': {'T3g': {'session': 'Li_T3g_053018_KSClusters',
    'Clustered': 0,
    'nCells': 0,
    'nMua': 0,
    'cell_IDs': {},
    'mua_IDs': {},
    'dateClustered': {},
    'unClustered_TTs': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    'All_TTs_Clustered': 0}},
  '053118': {'T3g': {'session': 'Li_T3g_053118_KSClusters',
    'Clustered': 0,
    'nCells': 0,
    'nMua': 0,
    'cell_IDs': {},
    'mua_IDs': {},
    'dateClustered': {},
    'unClustered_TTs': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    'All_TTs_Clustered': 0}},
  '060118': {'T3g': {'session': 'Li_T3g_060118_KSClusters',
    'Clustered': 1,
    'nCells': 9,
    'nMua': 17,
    'cell_IDs': {'1': [],
     '2': [],
     '3': [],
     '4': [],
     '5': [],
     '6': [],
     '7': [8, 10],
     '8': [10],
     '9': [],
     '10': [1, 2, 4, 6],
     '11': [],
     '12': [],
     '13': [3],
     '14': [2],
     '15': [],
     '16': []},
    'mua_IDs': {'1': [9],
     '2': [0],
     '3': [1, 2],
     '4': [],
     '5': [],
     '6': [3],
     '7': [],
     '8': [4, 6, 8, 9],
     '9': [6],
     '10': [0, 10, 11],
     '11': [],
     '12': [],
     '13': [4, 5, 9],
     '14': [0],
     '15': [],
     '16': []},
    'dateClustered': {'1': 'April 25 2019, 04:16PM',
     '2': 'April 25 2019, 04:16PM',
     '3': 'April 25 2019, 04:16PM',
     '4': 'April 25 2019, 04:16PM',
     '5': 'April 25 2019, 04:16PM',
     '6': 'April 25 2019, 04:16PM',
     '7': 'April 25 2019, 04:16PM',
     '8': 'April 25 2019, 04:16PM',
     '9': 'April 25 2019, 04:16PM',
     '10': 'April 25 2019, 04:16PM',
     '11': 'April 25 2019, 04:16PM',
     '12': 'April 25 2019, 04:16PM',
     '13': 'April 25 2019, 04:16PM',
     '14': 'April 25 2019, 04:16PM',
     '15': 'April 25 2019, 04:16PM',
     '16': 'April 25 2019, 04:16PM'},
    'unClustered_TTs': [],
    'All_TTs_Clustered': 1,
    'dateSummary': 'May 13 2019, 04:20PM'}},
  '060418': {'T3g': {'session': 'Li_T3g_060418_KSClusters',
    'Clustered': 1,
    'nCells': 5,
    'nMua': 17,
    'cell_IDs': {'1': [],
     '2': [],
     '3': [1, 8],
     '4': [],
     '5': [],
     '6': [],
     '7': [0],
     '8': [7, 8],
     '9': [],
     '10': [],
     '11': [],
     '12': [],
     '13': [],
     '14': [],
     '15': [],
     '16': []},
    'mua_IDs': {'1': [0, 3],
     '2': [8, 9],
     '3': [2],
     '4': [9, 10],
     '5': [10],
     '6': [0],
     '7': [],
     '8': [],
     '9': [],
     '10': [2, 5, 6, 7, 9],
     '11': [],
     '12': [],
     '13': [],
     '14': [0, 3, 10],
     '15': [],
     '16': []},
    'dateClustered': {'1': 'April 25 2019, 04:16PM',
     '2': 'April 25 2019, 04:16PM',
     '3': 'April 25 2019, 04:16PM',
     '4': 'April 25 2019, 04:16PM',
     '5': 'April 25 2019, 04:16PM',
     '6': 'April 25 2019, 04:16PM',
     '7': 'April 25 2019, 04:16PM',
     '8': 'April 25 2019, 04:16PM',
     '9': 'April 25 2019, 04:16PM',
     '10': 'April 25 2019, 04:16PM',
     '11': 'April 25 2019, 04:16PM',
     '12': 'April 25 2019, 04:16PM',
     '13': 'April 25 2019, 04:16PM',
     '14': 'April 25 2019, 04:16PM',
     '15': 'April 25 2019, 04:16PM',
     '16': 'April 25 2019, 04:16PM'},
    'unClustered_TTs': [],
    'All_TTs_Clustered': 1,
    'dateSummary': 'May 13 2019, 04:20PM'}},
  '060518': {'T3i': {'session': 'Li_T3i_060518_KSClusters',
    'Clustered': 0,
    'nCells': 0,
    'nMua': 0,
    'cell_IDs': {},
    'mua_IDs': {},
    'dateClustered': {},
    'unClustered_TTs': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    'All_TTs_Clustered': 0}},
  '060718': {'OF': {'session': 'Li_OF_060718_KSClusters',
    'Clustered': 0,
    'nCells': 0,
    'nMua': 0,
    'cell_IDs': {},
    'mua_IDs': {},
    'dateClustered': {},
    'unClustered_TTs': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    'All_TTs_Clustered': 0}},
  '060818': {'T3i': {'session': 'Li_T3i_060818_KSClusters',
    'Clustered': 0,
    'nCells': 0,
    'nMua': 0,
    'cell_IDs': {},
    'mua_IDs': {},
    'dateClustered': {},
    'unClustered_TTs': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    'All_TTs_Clustered': 0}},
  '061118': {'T3i': {'session': 'Li_T3i_061118_KSClusters',
    'Clustered': 0,
    'nCells': 0,
    'nMua': 0,
    'cell_IDs': {},
    'mua_IDs': {},
    'dateClustered': {},
    'unClustered_TTs': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    'All_TTs_Clustered': 0}},
  '061218': {'T3i': {'session': 'Li_T3i_061218_KSClusters',
    'Clustered': 0,
    'nCells': 0,
    'nMua': 0,
    'cell_IDs': {},
    'mua_IDs': {},
    'dateClustered': {},
    'unClustered_TTs': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    'All_TTs_Clustered': 0}},
  '061318': {'T3g': {'session': 'Li_T3g_061318_KSClusters',
    'Clustered': 1,
    'nCells': 6,
    'nMua': 11,
    'cell_IDs': {'1': [],
     '2': [],
     '3': [9],
     '4': [],
     '5': [],
     '6': [],
     '7': [4, 8],
     '8': [10],
     '9': [0],
     '10': [],
     '11': [],
     '12': [],
     '13': [],
     '14': [0],
     '15': [],
     '16': []},
    'mua_IDs': {'1': [8],
     '2': [8],
     '3': [0, 1, 7],
     '4': [6],
     '5': [],
     '6': [11],
     '7': [],
     '8': [1],
     '9': [11],
     '10': [5, 10],
     '11': [],
     '12': [],
     '13': [],
     '14': [],
     '15': [],
     '16': []},
    'dateClustered': {'1': 'April 25 2019, 04:16PM',
     '2': 'April 25 2019, 04:16PM',
     '3': 'April 25 2019, 04:16PM',
     '4': 'April 25 2019, 04:16PM',
     '5': 'April 25 2019, 04:16PM',
     '6': 'April 25 2019, 04:16PM',
     '7': 'April 25 2019, 04:16PM',
     '8': 'April 25 2019, 04:16PM',
     '9': 'April 25 2019, 04:16PM',
     '10': 'April 25 2019, 04:16PM',
     '11': 'April 25 2019, 04:16PM',
     '12': 'April 25 2019, 04:16PM',
     '13': 'April 25 2019, 04:16PM',
     '14': 'April 25 2019, 04:16PM',
     '15': 'April 25 2019, 04:16PM',
     '16': 'April 25 2019, 04:16PM'},
    'unClustered_TTs': [],
    'All_TTs_Clustered': 1,
    'dateSummary': 'May 13 2019, 04:20PM'}},
  '061418': {'OF': {'session': 'Li_OF_061418_KSClusters',
    'Clustered': 0,
    'nCells': 0,
    'nMua': 0,
    'cell_IDs': {},
    'mua_IDs': {},
    'dateClustered': {},
    'unClustered_TTs': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    'All_TTs_Clustered': 0}},
  '061518': {'T3g': {'session': 'Li_T3g_061518_KSClusters',
    'Clustered': 1,
    'nCells': 3,
    'nMua': 12,
    'cell_IDs': {'1': [],
     '2': [],
     '3': [1],
     '4': [],
     '5': [],
     '6': [],
     '7': [],
     '8': [8],
     '9': [],
     '10': [],
     '11': [],
     '12': [],
     '13': [],
     '14': [10],
     '15': [],
     '16': []},
    'mua_IDs': {'1': [],
     '2': [4, 5],
     '3': [0, 4],
     '4': [11],
     '5': [],
     '6': [10],
     '7': [3, 11],
     '8': [3],
     '9': [6, 9],
     '10': [],
     '11': [],
     '12': [],
     '13': [],
     '14': [8],
     '15': [],
     '16': []},
    'dateClustered': {'1': 'April 25 2019, 04:16PM',
     '2': 'April 25 2019, 04:16PM',
     '3': 'April 25 2019, 04:16PM',
     '4': 'April 25 2019, 04:16PM',
     '5': 'April 25 2019, 04:16PM',
     '6': 'April 25 2019, 04:16PM',
     '7': 'April 25 2019, 04:16PM',
     '8': 'April 25 2019, 04:16PM',
     '9': 'April 25 2019, 04:16PM',
     '10': 'April 25 2019, 04:16PM',
     '11': 'April 25 2019, 04:16PM',
     '12': 'April 25 2019, 04:16PM',
     '13': 'April 25 2019, 04:16PM',
     '14': 'April 25 2019, 04:16PM',
     '15': 'April 25 2019, 04:16PM',
     '16': 'April 25 2019, 04:16PM'},
    'unClustered_TTs': [],
    'All_TTs_Clustered': 1,
    'dateSummary': 'May 13 2019, 04:20PM'}},
  '061818': {'T3g': {'session': 'Li_T3g_061818_KSClusters',
    'Clustered': 1,
    'nCells': 8,
    'nMua': 14,
    'cell_IDs': {'1': [],
     '2': [],
     '3': [10],
     '4': [],
     '5': [],
     '6': [],
     '7': [2],
     '8': [0, 2, 4],
     '9': [],
     '10': [10],
     '11': [],
     '12': [],
     '13': [],
     '14': [0, 3],
     '15': [],
     '16': []},
    'mua_IDs': {'1': [],
     '2': [7],
     '3': [1, 6, 7],
     '4': [],
     '5': [],
     '6': [5, 9],
     '7': [8],
     '8': [9],
     '9': [6],
     '10': [6, 7],
     '11': [],
     '12': [],
     '13': [0],
     '14': [7, 9],
     '15': [],
     '16': []},
    'dateClustered': {'1': 'April 25 2019, 04:16PM',
     '2': 'April 25 2019, 04:16PM',
     '3': 'April 25 2019, 04:16PM',
     '4': 'April 25 2019, 04:16PM',
     '5': 'April 25 2019, 04:16PM',
     '6': 'April 25 2019, 04:16PM',
     '7': 'April 25 2019, 04:16PM',
     '8': 'April 25 2019, 04:16PM',
     '9': 'April 25 2019, 04:16PM',
     '10': 'April 25 2019, 04:16PM',
     '11': 'April 25 2019, 04:16PM',
     '12': 'April 25 2019, 04:16PM',
     '13': 'April 25 2019, 04:16PM',
     '14': 'April 25 2019, 04:16PM',
     '15': 'April 25 2019, 04:16PM',
     '16': 'April 25 2019, 04:16PM'},
    'unClustered_TTs': [],
    'All_TTs_Clustered': 1,
    'dateSummary': 'May 13 2019, 04:20PM'}},
  '062018': {'T3g': {'session': 'Li_T3g_062018_KSClusters',
    'Clustered': 1,
    'nCells': 10,
    'nMua': 12,
    'cell_IDs': {'1': [],
     '2': [],
     '3': [],
     '4': [],
     '5': [],
     '6': [],
     '7': [10],
     '8': [5, 6],
     '9': [4, 9],
     '10': [0, 6, 7, 9],
     '11': [],
     '12': [],
     '13': [],
     '14': [7],
     '15': [],
     '16': []},
    'mua_IDs': {'1': [10],
     '2': [0, 4, 7],
     '3': [4, 6],
     '4': [0],
     '5': [],
     '6': [],
     '7': [6],
     '8': [],
     '9': [],
     '10': [1, 2, 3],
     '11': [],
     '12': [],
     '13': [],
     '14': [8],
     '15': [],
     '16': []},
    'dateClustered': {'1': 'April 25 2019, 04:16PM',
     '2': 'April 25 2019, 04:16PM',
     '3': 'April 25 2019, 04:16PM',
     '4': 'April 25 2019, 04:16PM',
     '5': 'April 25 2019, 04:16PM',
     '6': 'April 25 2019, 04:16PM',
     '7': 'April 25 2019, 04:16PM',
     '8': 'April 25 2019, 04:16PM',
     '9': 'April 25 2019, 04:16PM',
     '10': 'April 25 2019, 04:16PM',
     '11': 'April 25 2019, 04:16PM',
     '12': 'April 25 2019, 04:16PM',
     '13': 'April 25 2019, 04:16PM',
     '14': 'April 25 2019, 04:16PM',
     '15': 'April 25 2019, 04:16PM',
     '16': 'April 25 2019, 04:16PM'},
    'unClustered_TTs': [],
    'All_TTs_Clustered': 1,
    'dateSummary': 'May 13 2019, 04:20PM'}},
  '062518': {'T3g': {'session': 'Li_T3g_062518_KSClusters',
    'Clustered': 1,
    'nCells': 10,
    'nMua': 16,
    'cell_IDs': {'1': [],
     '2': [],
     '3': [3, 8],
     '4': [],
     '5': [],
     '6': [],
     '7': [],
     '8': [4, 7],
     '9': [0],
     '10': [0, 5, 6],
     '11': [],
     '12': [],
     '13': [],
     '14': [7, 11],
     '15': [],
     '16': []},
    'mua_IDs': {'1': [0],
     '2': [0, 11],
     '3': [0, 1, 2, 7, 9],
     '4': [3],
     '5': [],
     '6': [],
     '7': [0, 5],
     '8': [],
     '9': [4],
     '10': [7, 8, 9],
     '11': [],
     '12': [],
     '13': [],
     '14': [0],
     '15': [],
     '16': []},
    'dateClustered': {'1': 'April 25 2019, 04:16PM',
     '2': 'April 25 2019, 04:16PM',
     '3': 'April 25 2019, 04:16PM',
     '4': 'April 25 2019, 04:16PM',
     '5': 'April 25 2019, 04:16PM',
     '6': 'April 25 2019, 04:16PM',
     '7': 'April 25 2019, 04:16PM',
     '8': 'April 25 2019, 04:16PM',
     '9': 'April 25 2019, 04:16PM',
     '10': 'April 25 2019, 04:16PM',
     '11': 'April 25 2019, 04:16PM',
     '12': 'April 25 2019, 04:16PM',
     '13': 'April 25 2019, 04:16PM',
     '14': 'April 25 2019, 04:16PM',
     '15': 'April 25 2019, 04:16PM',
     '16': 'April 25 2019, 04:16PM'},
    'unClustered_TTs': [],
    'All_TTs_Clustered': 1,
    'dateSummary': 'May 13 2019, 04:20PM'}},
  '062618': {'T3g': {'session': 'Li_T3g_062618_KSClusters',
    'Clustered': 1,
    'nCells': 9,
    'nMua': 17,
    'cell_IDs': {'1': [],
     '2': [8],
     '3': [7],
     '4': [],
     '5': [],
     '6': [],
     '7': [10],
     '8': [11],
     '9': [],
     '10': [1, 2, 5, 7, 10],
     '11': [],
     '12': [],
     '13': [],
     '14': [],
     '15': [],
     '16': []},
    'mua_IDs': {'1': [7],
     '2': [5],
     '3': [1, 4, 6, 8],
     '4': [0],
     '5': [],
     '6': [],
     '7': [3],
     '8': [2],
     '9': [5, 7],
     '10': [0, 3, 8, 9],
     '11': [],
     '12': [],
     '13': [],
     '14': [2, 7],
     '15': [],
     '16': []},
    'dateClustered': {'1': 'April 25 2019, 04:16PM',
     '2': 'April 25 2019, 04:16PM',
     '3': 'April 25 2019, 04:16PM',
     '4': 'April 25 2019, 04:16PM',
     '5': 'April 25 2019, 04:16PM',
     '6': 'April 25 2019, 04:16PM',
     '7': 'April 25 2019, 04:16PM',
     '8': 'April 25 2019, 04:16PM',
     '9': 'April 25 2019, 04:16PM',
     '10': 'April 25 2019, 04:16PM',
     '11': 'April 25 2019, 04:16PM',
     '12': 'April 25 2019, 04:16PM',
     '13': 'April 25 2019, 04:16PM',
     '14': 'April 25 2019, 04:16PM',
     '15': 'April 25 2019, 04:16PM',
     '16': 'April 25 2019, 04:16PM'},
    'unClustered_TTs': [],
    'All_TTs_Clustered': 1,
    'dateSummary': 'May 13 2019, 04:20PM'}},
  '062718': {'T3g': {'session': 'Li_T3g_062718_KSClusters',
    'Clustered': 1,
    'nCells': 16,
    'nMua': 13,
    'cell_IDs': {'1': [],
     '2': [],
     '3': [0, 2, 8],
     '4': [],
     '5': [],
     '6': [],
     '7': [],
     '8': [0, 2, 3, 4, 5, 8, 11],
     '9': [],
     '10': [7, 8, 9, 10],
     '11': [],
     '12': [],
     '13': [],
     '14': [2, 11],
     '15': [],
     '16': []},
    'mua_IDs': {'1': [2],
     '2': [],
     '3': [6, 7],
     '4': [5],
     '5': [],
     '6': [],
     '7': [8],
     '8': [1],
     '9': [],
     '10': [1, 3, 5],
     '11': [],
     '12': [],
     '13': [],
     '14': [0, 1, 6],
     '15': [9],
     '16': []},
    'dateClustered': {'1': 'April 25 2019, 04:16PM',
     '2': 'April 25 2019, 04:16PM',
     '3': 'April 25 2019, 04:16PM',
     '4': 'April 25 2019, 04:16PM',
     '5': 'April 25 2019, 04:16PM',
     '6': 'April 25 2019, 04:16PM',
     '7': 'April 25 2019, 04:16PM',
     '8': 'April 25 2019, 04:16PM',
     '9': 'April 25 2019, 04:16PM',
     '10': 'April 25 2019, 04:16PM',
     '11': 'April 25 2019, 04:16PM',
     '12': 'April 25 2019, 04:16PM',
     '13': 'April 25 2019, 04:16PM',
     '14': 'April 25 2019, 04:16PM',
     '15': 'April 25 2019, 04:16PM',
     '16': 'April 25 2019, 04:16PM'},
    'unClustered_TTs': [],
    'All_TTs_Clustered': 1,
    'dateSummary': 'May 13 2019, 04:20PM'}},
  '062818': {'T3g': {'session': 'Li_T3g_062818_KSClusters',
    'Clustered': 1,
    'nCells': 10,
    'nMua': 16,
    'cell_IDs': {'1': [],
     '2': [],
     '3': [1, 6],
     '4': [],
     '5': [],
     '6': [],
     '7': [3],
     '8': [4, 10],
     '9': [2],
     '10': [0, 6, 8],
     '11': [],
     '12': [],
     '13': [],
     '14': [9],
     '15': [],
     '16': []},
    'mua_IDs': {'1': [7],
     '2': [2, 10],
     '3': [0, 3],
     '4': [2],
     '5': [],
     '6': [3],
     '7': [],
     '8': [3],
     '9': [11],
     '10': [4, 5, 7, 9],
     '11': [],
     '12': [],
     '13': [],
     '14': [1, 8, 10],
     '15': [],
     '16': []},
    'dateClustered': {'1': 'April 25 2019, 04:16PM',
     '2': 'April 25 2019, 04:16PM',
     '3': 'April 25 2019, 04:16PM',
     '4': 'April 25 2019, 04:16PM',
     '5': 'April 25 2019, 04:16PM',
     '6': 'April 25 2019, 04:16PM',
     '7': 'April 25 2019, 04:16PM',
     '8': 'April 25 2019, 04:16PM',
     '9': 'April 25 2019, 04:16PM',
     '10': 'April 25 2019, 04:16PM',
     '11': 'April 25 2019, 04:16PM',
     '12': 'April 25 2019, 04:16PM',
     '13': 'April 25 2019, 04:16PM',
     '14': 'April 25 2019, 04:16PM',
     '15': 'April 25 2019, 04:16PM',
     '16': 'April 25 2019, 04:16PM'},
    'unClustered_TTs': [],
    'All_TTs_Clustered': 1,
    'dateSummary': 'May 13 2019, 04:20PM'}},
  '062918': {'OF': {'session': 'Li_OF_062918_KSClusters',
    'Clustered': 0,
    'nCells': 0,
    'nMua': 0,
    'cell_IDs': {},
    'mua_IDs': {},
    'dateClustered': {},
    'unClustered_TTs': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    'All_TTs_Clustered': 0}},
  '070218': {'T3g': {'session': 'Li_T3g_070218_KSClusters',
    'Clustered': 0,
    'nCells': 0,
    'nMua': 0,
    'cell_IDs': {},
    'mua_IDs': {},
    'dateClustered': {},
    'unClustered_TTs': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    'All_TTs_Clustered': 0}},
  '070618': {'T3g': {'session': 'Li_T3g_070618_KSClusters',
    'Clustered': 0,
    'nCells': 0,
    'nMua': 0,
    'cell_IDs': {},
    'mua_IDs': {},
    'dateClustered': {},
    'unClustered_TTs': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    'All_TTs_Clustered': 0}},
  '071018': {'T3g': {'session': 'Li_T3g_071018_KSClusters',
    'Clustered': 0,
    'nCells': 0,
    'nMua': 0,
    'cell_IDs': {},
    'mua_IDs': {},
    'dateClustered': {},
    'unClustered_TTs': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    'All_TTs_Clustered': 0}},
  '080118': {'T3g': {'session': 'Li_T3g_080118_KSClusters',
    'Clustered': 0,
    'nCells': 0,
    'nMua': 0,
    'cell_IDs': {},
    'mua_IDs': {},
    'dateClustered': {},
    'unClustered_TTs': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    'All_TTs_Clustered': 0}},
  '080218': {'T3g': {'session': 'Li_T3g_080218_KSClusters',
    'Clustered': 0,
    'nCells': 0,
    'nMua': 0,
    'cell_IDs': {},
    'mua_IDs': {},
    'dateClustered': {},
    'unClustered_TTs': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    'All_TTs_Clustered': 0}},
  '070518': {'T3g': {'session': 'Li_T3g_070518_KSClusters',
    'Clustered': 0,
    'nCells': 0,
    'nMua': 0,
    'cell_IDs': {},
    'mua_IDs': {},
    'dateClustered': {},
    'unClustered_TTs': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    'All_TTs_Clustered': 0}},
  '070918': {'T3g': {'session': 'Li_T3g_070918_KSClusters',
    'Clustered': 0,
    'nCells': 0,
    'nMua': 0,
    'cell_IDs': {},
    'mua_IDs': {},
    'dateClustered': {},
    'unClustered_TTs': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    'All_TTs_Clustered': 0}},
  '071118': {'T3g': {'session': 'Li_T3g_071118_KSClusters',
    'Clustered': 0,
    'nCells': 0,
    'nMua': 0,
    'cell_IDs': {},
    'mua_IDs': {},
    'dateClustered': {},
    'unClustered_TTs': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    'All_TTs_Clustered': 0}},
  '072518': {'T3g': {'session': 'Li_T3g_072518_KSClusters',
    'Clustered': 0,
    'nCells': 0,
    'nMua': 0,
    'cell_IDs': {},
    'mua_IDs': {},
    'dateClustered': {},
    'unClustered_TTs': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    'All_TTs_Clustered': 0}},
  '072618': {'T3g': {'session': 'Li_T3g_072618_KSClusters',
    'Clustered': 0,
    'nCells': 0,
    'nMua': 0,
    'cell_IDs': {},
    'mua_IDs': {},
    'dateClustered': {},
    'unClustered_TTs': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    'All_TTs_Clustered': 0}},
  '073018': {'T3g': {'session': 'Li_T3g_073018_KSClusters',
    'Clustered': 0,
    'nCells': 0,
    'nMua': 0,
    'cell_IDs': {},
    'mua_IDs': {},
    'dateClustered': {},
    'unClustered_TTs': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    'All_TTs_Clustered': 0}},
  '080318': {'T3g': {'session': 'Li_T3g_080318_KSClusters',
    'Clustered': 0,
    'nCells': 0,
    'nMua': 0,
    'cell_IDs': {},
    'mua_IDs': {},
    'dateClustered': {},